### ISSUE TITLE
DOI for EVHR Repository

### ISSUE THREAD

**Issue by jordancaraballo** [nasa-nccs-hpda/evhr#11]
I have our organization connected to Zenodo. I have enabled DOI creation for this repository. Once you generate the new release for EVHR via Github, I will attach a DOI tag to this issue so you can add it to the README.

**Comment by jordancaraballo** [comment]
@cssprad1 @evhrgh Hey guys, we need a Github release ASAP so @pahbs  can cite the EVHR repo on the SRLite paper. All I need is a Github release and the DOI will. be generated automatically.

**Comment by cssprad1** [comment]
Done, if the DOI was created then go ahead and close out this issue.

**Comment by jordancaraballo** [comment]
Attaching the badge here for README modifications. Will close the ticket after modifications to the README.

[![DOI](https://zenodo.org/badge/325633657.svg)](https://zenodo.org/doi/10.5281/zenodo.10062470)

**Comment by jordancaraballo** [comment]
Commit d13a191 takes care of this. Closing this issue.
