### ISSUE TITLE
DG Mosaic Application Permissions

### ISSUE THREAD

**Issue by evhrgh** [nasa-nccs-hpda/evhr#26]
There was a suggestion that dg_mosaic failed to run under circumstances that were not reported, and that whatever the symptom, the cure is to ensure the application has sufficient file-system privileges for all to run it.  Indeed, the group permission disallows execution, as seen below.

$ singularity shell -B /explore/nobackup/people,/explore/nobackup/projects,/css,/nfs4m,/tmp, /explore/nobackup/people/iluser/ilab_containers/evhr_4.0.0.sif
Singularity> ls -al /opt/StereoPipeline/bin/dg_mosaic 
-rwxr--r-x. 1 someone ilab 1578 Jul 29  2020 /opt/StereoPipeline/bin/dg_mosaic

When building the container, set those permissions to 755.  We will see if there are similar complaints in the future, since we have not advice how to replicate the symptom.

**Comment by ssfinch** [comment]
Created new container version 4.0.1 with updated /opt permissions:

[sstrong@ilab201 ~]$ singularity shell -B /explore/nobackup/people,/explore/nobackup/projects,/css,/nfs4m,/tmp, /explore/nobackup/people/iluser/ilab_containers/evhr_4.0.1.sif

Singularity> cd /opt
Singularity> ls -alt
total 0
**drwxr-xr-x**. 6 sstrong ilab 0 Mar  8 11:27 DgStereo
**drwxr-xr-x**. 9 sstrong ilab 0 Jul 29  2020 StereoPipeline

Tested evhr application in container and it completed successfully..

Singularity> time python /usr/local/ilab/evhr/view/evhrToaCLV.py -o /explore/nobackup/projects/ilab/ilab_testing/evhr/output/4.0.1 --scenes /css/nga/WV03/1B/2015/219/WV03_104001000F2D9E00_X1BS_500495393030_01/WV03_20150807213524_104001000F2D9E00_15AUG07213524-M1BS-500495393030_01_P001.ntf

Created output directories correctly:

[sstrong@ilab201 4.0.1]$ pwd
/explore/nobackup/projects/ilab/ilab_testing/evhr/output/4.0.1
[sstrong@ilab201 4.0.1]$ l
total 256
drwxr-x---.  2 sstrong ilab 8192 Mar  8 11:51 2-strips
drwxr-x---.  2 sstrong ilab 8192 Mar  8 11:51 4-orthos
drwxr-x---.  2 sstrong ilab 4096 Mar  8 11:51 5-toas
drwxr-x---.  2 sstrong ilab 4096 Mar  8 11:45 3-dems
drwxr-x---.  2 sstrong ilab 4096 Mar  8 11:45 1-bands
drwxr-x---.  7 sstrong ilab 4096 Mar  8 11:38 .
drwxr-xr-x. 15 sstrong ilab 4096 Mar  8 11:37 ..
